project:
  type: website
  output-dir: ../docs
  resources:
  - js/

website:
  title: "today"
  search: false
  navbar:
    left:
      - href: videos.qmd
        text: Videos
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  