project:
  type: website
  output-dir: ../docs
  resources:
  - js/

website:
  title: "Greenbank"
  search: false
  navbar:
    left:
      - href: videos.qmd
        text: Videos

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  
execute:
  echo: false