services:

  colmap:
    image: colmap/colmap:latest
    runtime: nvidia
    volumes:
      - ../data:/data
    command: bash

  openmvg:
    build:
      context: .
      dockerfile: Dockerfile.openmvg
    runtime: nvidia
    volumes:
      - ../data:/data
    command: bash

  openmvs:
      build:
        context: .
        dockerfile: Dockerfile.openmvs
      runtime: nvidia
      volumes:
      - ../data:/data
      command: bash