services:

  colmap:
    build:
      context: .
      dockerfile: Dockerfile.colmap
    runtime: nvidia
    volumes:
      - ../data:/data
    command: bash
    environment:
    - QT_QPA_PLATFORM=offscreen

  colmap-cuda:
    build:
      context: .
      dockerfile: Dockerfile.colmap.cuda
    runtime: nvidia
    volumes:
      - ../data:/data
    command: bash
    environment:
    - QT_QPA_PLATFORM=offscreen

  openmvg:
    build:
      context: .
      dockerfile: Dockerfile.openmvg
    runtime: nvidia
    volumes:
      - ../data:/data
    command: bash

  openmvs:
      build:
        context: .
        dockerfile: Dockerfile.openmvs
      runtime: nvidia
      volumes:
      - ../data:/data
      command: bash